### ISSUE TITLE
Port uploading process for normal/tumor samples rather than proband/unaffected

### ISSUE THREAD

**Issue by stefinfection** [iobio/oncogene#1]

**Comment by stefinfection** [comment]
What format will the vcf data be presented in?

1. Multi-sample vcf where individual samples correspond to normal and tumor samples
2. Individual vcfs: one per every normal and tumor sample

**Comment by yiq** [comment]
I’d advocate for multisample vcf since otherwise it’s hard to find out e.g. a somatic variant is not in the normal because it’s truly somatic, or because there was insufficient coverage in the normal

**Comment by stefinfection** [comment]
Incorporate saving/uploading JSON file to allow return users/projects to one-button upload
